name:                FunHAL
version:             0.1.0.0
github:              "githubuser/FunHAL"
license:             BSD3
author:              "BERNARD Damien"
maintainer:          "damien.bernard@epitech.eu"
copyright:           "2020 BERNARD Damien VEYRENC Quentin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/FunHAL#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs:
    - src
    - lib
  dependencies:
    - haskeline
    - containers



executables:
  hal:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -optc-O3
    - -O2
    dependencies:
    - FunHAL

tests:
#  hal-test:
  FunHAL-tests:
    main:                Spec.hs
    source-dirs:         tests/ut
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FunHAL
    - QuickCheck
    - hspec
