name:                FunHAL
version:             0.1.0.0
github:              "githubuser/FunHAL"
license:             BSD3
author:              "BERNARD Damien"
maintainer:          "damien.bernard@epitech.eu"
copyright:           "2020 BERNARD Damien"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/FunHAL#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hal:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FunHAL

tests:
  hal-test:
    main:                Spec.hs
    source-dirs:         tests/ut
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FunHAL
