name: Build

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make
      - name: make re
        run: make re
      - name: make tests
        run: make tests
      - name: make func_tests
        run: make func_tests
